#Targetname : Dependent target names
#<TAB>command

Build:
	gcc src\src.c src\func1.c src\func2.c -Isrc test\test_ATM_management.c -Itest Unity\unity.c -IUnity inc\Atm_management.h -Iinc

Run:
	src\a.exe